import {
    Code, Briefcase, Cpu, Palette, BarChart, Zap, Bot, Megaphone,
    Infinity, Award, Clock, TrendingUp,
    Terminal, Server, Smartphone, AppWindow, Rocket, Table,
    Stars, MessageSquare, Layers, FileCode, Braces, Repeat, Palette as PaletteIcon, PenTool, Layout
} from "lucide-react";
import { CourseProps } from "@/components/CourseCard";

export const categories = [
    { title: "Development", slug: "development", icon: <Code /> },
    { title: "Business", slug: "business", icon: <Briefcase /> },
    { title: "Tech & IT", slug: "development", icon: <Cpu /> },
    { title: "Creativity", slug: "design", icon: <Palette /> },
    { title: "Data Science", slug: "data-science", icon: <BarChart /> },
    { title: "Productivity", slug: "productivity", icon: <Zap /> },
    { title: "AI & Prompt Engineering", slug: "ai", icon: <Bot /> },
    { title: "Marketing", slug: "marketing", icon: <Megaphone /> },
];

export const features = [
    { title: "Lifetime Access", description: "Learn at your own pace with unlimited access to all course materials.", icon: <Infinity /> },
    { title: "Certification", description: "Earn certificates upon completion to showcase your new skills.", icon: <Award /> },
    { title: "Learn at Your Own Pace", description: "Study whenever and wherever you want, on any device.", icon: <Clock /> },
    { title: "Beginner to Advanced", description: "Courses for all skill levels, from complete beginners to experts.", icon: <TrendingUp /> },
];

export const courses: CourseProps[] = [
    {
        id: "1",
        title: "AI Prompt Engineering Basics",
        instructor: "Video Creator",
        rating: 4.5,
        price: 199,
        category: "ai",
        level: "beginner",
        icon: <Bot size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/AI Prompt Engineering Basics.pdf",
        image: "/assets/ai_prompt_engineering_course_thumbnail_1768397830024.png"
    },
    {
        id: "2",
        title: "Advanced Prompt Engineering",
        instructor: "Video Creator",
        rating: 4.8,
        price: 299,
        category: "ai",
        level: "advanced",
        icon: <Stars size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/Advanced Prompt Engineering.pdf",
        image: "/assets/advanced_prompt_engineering_thumbnail_1768399009730.png"
    },
    {
        id: "3",
        title: "ChatGPT Mastery Course",
        instructor: "Video Creator",
        rating: 4.7,
        price: 249,
        category: "ai",
        level: "intermediate",
        icon: <MessageSquare size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/ChatGPT Mastery Course.pdf",
        image: "/assets/chatgpt_mastery_thumbnail_1768399037483.png"
    },
    {
        id: "4",
        title: "Complete MERN Stack Development",
        instructor: "Video Creator",
        rating: 4.9,
        price: 4999,
        category: "development",
        level: "advanced",
        icon: <Layers size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/Complete MERN Stack Development.pdf",
        image: "/assets/mern_stack_course_thumbnail_1768397860702.png"
    },
    {
        id: "5",
        title: "Advanced MERN Stack Projects",
        instructor: "Video Creator",
        rating: 4.8,
        price: 3499,
        category: "development",
        level: "advanced",
        icon: <Terminal size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Advanced MERN Stack Projects.pdf",
        image: "/assets/advanced_mern_stack_projects_thumbnail_1768399061289.png"
    },
    {
        id: "6",
        title: "Python Programming for Beginners",
        instructor: "Video Creator",
        rating: 4.6,
        price: 999,
        category: "development",
        level: "beginner",
        icon: <FileCode size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/Python Programming for Beginners.pdf",
        image: "/assets/python_programming_course_thumbnail_1768397891530.png"
    },
    {
        id: "7",
        title: "Python for Data Science",
        instructor: "Video Creator",
        rating: 4.7,
        price: 2499,
        category: "data-science",
        level: "intermediate",
        icon: <BarChart size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Python for Data Science.pdf",
        image: "/assets/python_data_science_thumbnail_1768399091961.png"
    },
    {
        id: "8",
        title: "JavaScript Fundamentals",
        instructor: "Video Creator",
        rating: 4.5,
        price: 899,
        category: "development",
        level: "beginner",
        icon: <Braces size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/JavaScript Fundamentals.pdf",
        image: "/assets/javascript_fundamentals_course_thumbnail_1768397921893.png"
    },
    {
        id: "9",
        title: "Advanced JavaScript & ES6+",
        instructor: "Video Creator",
        rating: 4.8,
        price: 1999,
        category: "development",
        level: "advanced",
        icon: <Terminal size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Advanced JavaScript & ES6+.pdf",
        image: "/assets/advanced_javascript_thumbnail_1768399115054.png"
    },
    {
        id: "10",
        title: "Complete React Development",
        instructor: "Video Creator",
        rating: 4.9,
        price: 2999,
        category: "development",
        level: "intermediate",
        icon: <Repeat size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/Complete React Development.pdf",
        image: "/assets/complete_react_development_thumbnail_1768399140636.png"
    },
    {
        id: "11",
        title: "Node.js Backend Development",
        instructor: "Video Creator",
        rating: 4.7,
        price: 2499,
        category: "development",
        level: "intermediate",
        icon: <Server size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Node.js Backend Development.pdf",
        image: "/assets/nodejs_backend_development_thumbnail_1768399180679.png"
    },
    {
        id: "12",
        title: "UI/UX Design Fundamentals",
        instructor: "Video Creator",
        rating: 4.6,
        price: 1499,
        category: "design",
        level: "beginner",
        icon: <PaletteIcon size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/UI/UX Design Fundamentals.pdf",
        image: "/assets/ui_ux_design_course_thumbnail_1768397952998.png"
    },
    {
        id: "13",
        title: "Figma Design Mastery",
        instructor: "Video Creator",
        rating: 4.8,
        price: 1799,
        category: "design",
        level: "intermediate",
        icon: <PenTool size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Figma Design Mastery.pdf",
        image: "/assets/figma_design_mastery_thumbnail_1768399215142.png"
    },
    {
        id: "14",
        title: "Mobile App Development",
        instructor: "Video Creator",
        rating: 4.7,
        price: 3499,
        category: "development",
        level: "intermediate",
        icon: <Smartphone size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/Mobile App Development.pdf",
        image: "/assets/mobile_app_development_thumbnail_1768399237323.png"
    },
    {
        id: "15",
        title: "Flutter Complete Course",
        instructor: "Video Creator",
        rating: 4.8,
        price: 2999,
        category: "development",
        level: "intermediate",
        icon: <AppWindow size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Flutter Complete Course.pdf",
        image: "/assets/flutter_complete_course_thumbnail_1768399272399.png"
    },
    {
        id: "16",
        title: "Complete Freelancing Guide",
        instructor: "Video Creator",
        rating: 4.5,
        price: 799,
        category: "business",
        level: "beginner",
        icon: <Briefcase size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/Complete Freelancing Guide.pdf",
        image: "/assets/business_and_freelancing_thumbnail_1768398010304.png"
    },
    {
        id: "17",
        title: "Productivity Hacks & Time Management",
        instructor: "Video Creator",
        rating: 4.6,
        price: 599,
        category: "productivity",
        level: "beginner",
        icon: <Zap size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Productivity Hacks & Time Management.pdf",
        image: "/assets/productivity_hacks_thumbnail_1768399293481.png"
    },
    {
        id: "18",
        title: "Time Management Mastery",
        instructor: "Video Creator",
        rating: 4.4,
        price: 499,
        category: "productivity",
        level: "beginner",
        icon: <Clock size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/Time Management Mastery.pdf",
        image: "/assets/time_management_mastery_thumbnail_1768399316323.png"
    },
    {
        id: "19",
        title: "Digital Marketing Complete Course",
        instructor: "Video Creator",
        rating: 4.7,
        price: 1999,
        category: "marketing",
        level: "intermediate",
        icon: <Megaphone size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Digital Marketing Complete Course.pdf",
        image: "/assets/digital_marketing_course_thumbnail_1768397983870.png"
    },
    {
        id: "20",
        title: "SEO Mastery & Google Rankings",
        instructor: "Video Creator",
        rating: 4.8,
        price: 1799,
        category: "marketing",
        level: "advanced",
        icon: <TrendingUp size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/SEO Mastery & Google Rankings.pdf",
        image: "/assets/seo_mastery_thumbnail_1768399351956.png"
    },
    {
        id: "21",
        title: "Data Analytics Complete Course",
        instructor: "Video Creator",
        rating: 4.7,
        price: 2999,
        category: "data-science",
        level: "intermediate",
        icon: <BarChart size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Data Analytics Complete Course.pdf",
        image: "/assets/data_analytics_complete_course_thumbnail_1768399383321.png"
    },
    {
        id: "22",
        title: "Advanced Excel for Professionals",
        instructor: "Video Creator",
        rating: 4.6,
        price: 1299,
        category: "productivity",
        level: "intermediate",
        icon: <Table size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/Advanced Excel for Professionals.pdf",
        image: "/assets/data_analytics_complete_course_thumbnail_1768399383321.png"
    },
    {
        id: "23",
        title: "Canva Design for Beginners",
        instructor: "Video Creator",
        rating: 4.5,
        price: 699,
        category: "design",
        level: "beginner",
        icon: <Layout size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Canva Design for Beginners.pdf",
        image: "/assets/canva course.jpg"
    },
    {
        id: "24",
        title: "No-Code Tools & App Building",
        instructor: "Video Creator",
        rating: 4.6,
        price: 1499,
        category: "development",
        level: "beginner",
        icon: <Code size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/No-Code Tools & App Building.pdf",
        image: "/assets/flutter_complete_course_thumbnail_1768399272399.png"
    },
    {
        id: "25",
        title: "Startup & Business Fundamentals",
        instructor: "Video Creator",
        rating: 4.8,
        price: 2499,
        category: "business",
        level: "intermediate",
        icon: <Rocket size={48} />,
        color: "#2D6DF6",
        pdfUrl: "/Courses/Startup & Business Fundamentals.pdf",
        image: "/assets/business_and_freelancing_thumbnail_1768398010304.png"
    },
    {
        id: "26",
        title: "2025 AI Productivity Masterclass",
        instructor: "Video Creator",
        rating: 5.0,
        price: 99,
        category: "productivity",
        level: "beginner",
        icon: <Bot size={48} />,
        color: "#00B894",
        pdfUrl: "/Courses/2025 AI Productivity Masterclass.pdf",
        image: "/assets/productivity_hacks_thumbnail_1768399293481.png"
    }
];
